Advanced cluster config
nitindermohan/oak-new-docs pull request #10
Opened 2024-11-20 21:13 UTC by Mjaethers

A guide on advanced cluster configuration. Includes using the standalone scripts, choosing a branch and the docker-compose overrides.

2024-11-21 10:16 UTC, Mjaethers commented
PR for the fixed standalone scripts [here](https://github.com/oakestra/oakestra/pull/367)

2024-11-25 14:03 UTC, giobart requested changes

2024-11-25 14:03 UTC, giobart commented on content/docs/manuals/advanced-cluster-setup.md
> +This script will download the required files to a directory called root_orchestrator. From there it will build the root orchestrator.
Depending on the outcome of this: https://github.com/oakestra/oakestra/pull/367#pullrequestreview-2458465480

This might need to be changed.

2024-11-25 14:03 UTC, giobart commented on content/docs/manuals/advanced-cluster-setup.md
> +configuring the cluster. One the setup is complete it will build the cluster orchestrator and register with the root orchestrator.
```suggestion
configuring the cluster. Once the setup is complete, it will build the cluster orchestrator and register with the root orchestrator.
```

2024-11-25 14:03 UTC, giobart commented on content/docs/manuals/advanced-cluster-setup.md
> +### Stand-alone Cluster Orchestrator
What if at the beginning of each section we add a picture like the one in `docs/getting-started/oak-environment/create-your-first-oakestra-orchestrator/` but where we obscure the components that we're not setting up? For example:
<img width="585" alt="image" src="https://github.com/user-attachments/assets/c89ba618-3f66-41e1-bf4b-7fff0f1dfe68">

The base drawio for this picture is available in `getting-started-oak-environment/arch.drawio`

2024-11-25 14:03 UTC, giobart commented on content/docs/manuals/advanced-cluster-setup.md
> +By default these scripts will build from the `main` oakestra branch. However this can be changed by setting the environment variable `OAKESTRA_BRANCH`.
This script is not building but it uses the pre-built images. The OAK_BRANCH changes the branch from where we take the compose files. 

```suggestion
By default these scripts will compose the services of the `main` oakestra branch, the latest stable release. However this can be changed by setting the environment variable `OAKESTRA_BRANCH` **before running the startup script**.
```

2024-11-25 14:03 UTC, giobart commented on content/docs/manuals/advanced-cluster-setup.md
> +This will allow you to build the newest Oakestra version.
```suggestion
This will allow you to use the services from the alpha Oakestra release.
```

2024-11-25 14:03 UTC, giobart commented on content/docs/manuals/advanced-cluster-setup.md
> +To use the override files, specify the them in a comma-seperated list:
```suggestion
To use the override files, specify the them in a comma-seperated list by setting the `OVERRIDE_FILES` env variable **before running the startup script**.
```

2024-11-28 10:46 UTC, Mjaethers commented
I had to rebase onto the dark-light mode SVG support branch, hence all the commits

2024-11-28 11:00 UTC, giobart commented
Do we need to merge this into getstarted or directly main?

2024-11-28 11:01 UTC, Mjaethers commented
No, this can be merged into main

2024-12-06 09:24 UTC, giobart requested changes
<img width="1398" alt="image" src="https://github.com/user-attachments/assets/859ace66-6215-4f46-90d0-dfc970b3ef54">

The PR is actually ready and looking veeery good. I only noticed 2 small artifacts with the Architecture figure
- the image is overflowing a bit on the right side
- the image fonts are not correct. Please make sue you have CMU Sans Serif font installed in your machine before exporting the picture. If necessary, re-apply it to the image

2024-12-09 18:15 UTC, Mjaethers commented
@Malyuk-A does PR #13 allow us to specify the size of the svg?

2024-12-11 13:45 UTC, nitindermohan requested changes
I have the same issue as pointed out by @giobart where the images are exceeding the page dimensions and overlapping the navigation on the right. 

@Malyuk-A is there a way to resolve it with your updates?

2024-12-11 13:45 UTC, nitindermohan commented on content/docs/manuals/advanced-cluster-setup.md
> +{{< callout context="danger" title="Note" icon="outline/alert-octagon" >}}
Maybe change the title to "Watch out!" as there is another Note callout underneath with a different color

2024-12-12 08:25 UTC, nitindermohan commented
@Mjaethers There are conflicts in this branch with main. Can you please take care of them?

2024-12-16 16:42 UTC, giobart requested changes
After mergin @Malyuk-A changes the images are perfect. 
My last request: in overrides, can we add the description for the override addons?  That's the one used here: https://github.com/nitindermohan/oak-new-docs/blob/a9cf3a1e4e5550bc667af7d582643823d361cf97/content/docs/manuals/extending-oakestra/prerequisite.md

2024-12-17 12:15 UTC, giobart commented
I moved the firewall page from getstarted to manuals and linked it inside this guide as well.

2024-12-17 12:16 UTC, giobart approved these changes

2024-12-17 16:53 UTC, nitindermohan commented
Directly made some changes to the branch (both UI and clarification). @Mjaethers please see if you agree with them.

2024-12-17 16:54 UTC, nitindermohan approved these changes
Approved after local changes

2024-12-17 20:54 UTC, Mjaethers commented
@nitindermohan I agree with the changes, this can be merged then?

2024-12-17 22:11 UTC, merged

2024-12-17 22:11 UTC, nitindermohan commented
Merged! Thanks @Mjaethers for all the good work!