Add custom dark/light mode SVG support
nitindermohan/oak-new-docs pull request #13
Opened 2024-11-22 13:08 UTC by Malyuk-A

After several hours of tinkering I conclude that the native dark-light toggle from Doks/Hugo is working - but the `inline-svg` is not compatible with "dark-mode" SVGs created via draw.io.

E.g. I created and provide only a dark mode option of an SVG but it was still rendered white.

So instead I added a new custom shortcode that does the trick. In addition you only need to provide the prefix name of the file.

E.g.:
```
Files:
- your_svg.drawio
- your_svg_dark.svg
- your_svg_light.svg

Embedded in the md files like this:

{{<svg "your_svg">}}
```

One has to place these files in the `static/svgs/` folder

Demo:

https://github.com/user-attachments/assets/566a3e3e-99e9-4805-865a-f9624ad4d3ae

https://github.com/user-attachments/assets/9094d84d-25c0-4284-8b56-7d5062bf8f59

2024-11-24 10:41 UTC, Mjaethers reviewed
Really really nice. Let's merge this ASAP so that we can start using it!

2024-11-24 10:41 UTC, Mjaethers commented on static/svgs/mqtt/MQTT-Arch.svg
Was keeping the previously light svg deliberate? Perhaps keeping a *.draw.io file makes it clear that this file can be imported into drawio, even if importing a drawio *.svg is not a problem.

2024-11-25 14:13 UTC, giobart requested changes

2024-11-25 14:13 UTC, giobart commented on assets/svgs/mqtt/MQTT-Arch.drawio
can we keep the .drawio files as well?

2024-11-27 11:49 UTC, Malyuk-A commented on static/svgs/mqtt/MQTT-Arch.svg
My bad - this should have been the .drawio file - maybe "file name typo" from my side - As described in the PR description I of course want to keep the drawio file :P

2024-11-27 11:49 UTC, Malyuk-A commented on assets/svgs/mqtt/MQTT-Arch.drawio
My bad - this should have been the .drawio file - maybe "file name typo" from my side - As described in the PR description, I of course, want to keep the drawio file :P

2024-11-27 11:52 UTC, giobart approved these changes

2024-11-27 11:53 UTC, giobart commented
Awesome! Feel free to merge, green light on my side

2024-11-27 11:54 UTC, merged