Debugging manuals
nitindermohan/oak-new-docs pull request #17
Opened 2024-11-26 16:51 UTC by giobart

Added debugging manuals covering:

- Control Plane observability
- Running Applications
- Networking
- VS Code Debuggin (draft mode activated, this manual release is deferred)

2024-12-11 00:17 UTC, nitindermohan requested changes
Please see inline comments, commits https://github.com/nitindermohan/oak-new-docs/commit/716a7df29318d22d5e3df01d196c7ae0fd814e11 and https://github.com/nitindermohan/oak-new-docs/commit/a9f2c67c52cad17cc874caf8bc8368c652633538 for changes

2024-12-11 00:17 UTC, nitindermohan commented on content/docs/manuals/debugging/control-plane.md
> +The cluster Grafana dashboard is not available for 1-DOC deployments. For 1-DOC all the data is aggregated in the same dashboard.
Are we still referencing 1-DOC? I thought that was overthrown with single machine and multiple machine deployment?

Please look into this and also add link to the setup doc

2024-12-11 00:17 UTC, nitindermohan commented on content/docs/manuals/debugging/control-plane.md
> +On Net Manager v0.4.203 and above you can access the logs at
Not sure if adding specific version in text is a good idea. Tie it down to the current version docs

2024-12-11 00:17 UTC, nitindermohan commented on content/docs/manuals/debugging/control-plane.md
> +In NetManager v0.4.302 or above add the debug `true` flag in your `netcfg.json` file as follows:
Same issue with versioning here

2024-12-11 00:17 UTC, nitindermohan commented on content/docs/manuals/debugging/control-plane.md
> +{{< callout context="note" title="v0.4.301 or previous releases" icon="outline/info-circle" >}}
Very version specific information. Maybe term it as "legacy"?

2024-12-11 10:44 UTC, giobart commented on content/docs/manuals/debugging/control-plane.md
> +The cluster Grafana dashboard is not available for 1-DOC deployments. For 1-DOC all the data is aggregated in the same dashboard.
true, I wrote this part before we changed naming. I'll fix this.

2024-12-11 10:49 UTC, giobart commented
> Please see inline comments, commits [716a7df](https://github.com/nitindermohan/oak-new-docs/commit/716a7df29318d22d5e3df01d196c7ae0fd814e11) and [a9f2c67](https://github.com/nitindermohan/oak-new-docs/commit/a9f2c67c52cad17cc874caf8bc8368c652633538) for changes

Why in commit [716a7df](https://github.com/nitindermohan/oak-new-docs/commit/716a7df29318d22d5e3df01d196c7ae0fd814e11)  the entire cluster logs sections was deleted?

2024-12-11 13:55 UTC, nitindermohan commented
@giobart Regarding https://github.com/nitindermohan/oak-new-docs/pull/17#issuecomment-2535505066,the deleted text was moved to the overview page: https://github.com/nitindermohan/oak-new-docs/blob/716a7df29318d22d5e3df01d196c7ae0fd814e11/content/docs/manuals/debugging/debugging-overview.md

2024-12-11 14:01 UTC, nitindermohan approved these changes
minor change in lettering but approved otherwise

2024-12-11 14:01 UTC, nitindermohan commented on content/docs/manuals/debugging/control-plane.md
> +{{< callout context="note" title="legacy v0.4.301 or previous releases" icon="outline/info-circle" >}}
in title "legacy" -> "Legacy"

2024-12-11 15:23 UTC, giobart commented on content/docs/manuals/debugging/control-plane.md
> +{{< callout context="note" title="legacy v0.4.301 or previous releases" icon="outline/info-circle" >}}
```suggestion
{{< callout context="note" title="Legacy v0.4.301 or previous releases" icon="outline/info-circle" >}}
```

2024-12-12 08:28 UTC, merged

2024-12-12 08:28 UTC, nitindermohan commented
Merged. Thanks for all the work @giobart