Orchestration concepts
nitindermohan/oak-new-docs pull request #18
Opened 2024-11-27 11:54 UTC by giobart

Working on orchestration concepts section

2024-12-16 13:36 UTC, giobart commented
To correctly render the table in the scheduling section, PR #27 must be merged.

2024-12-16 15:38 UTC, nitindermohan commented on content/docs/concepts/high-level-architecture.md
> +* The [Worker Node](#worker-node) composed of **NodeEngine**, and **Net Manager**
Maybe put this in a callout so it stands out?

2024-12-18 15:28 UTC, nitindermohan requested changes
@giobart made some changes directly for clarity. But also left some comments for you to handle

2024-12-18 15:28 UTC, nitindermohan commented on content/docs/concepts/high-level-architecture.md
> +* The [Worker Node](#worker-node) composed of **NodeEngine**, and **Net Manager**, manages the workloads.
```suggestion
* The [Worker Node](#worker-node) machine that executes application microservices.
```

2024-12-18 15:28 UTC, nitindermohan commented on content/docs/concepts/high-level-architecture.md
> +and docker compose plugin is used to integrate and run them.
```suggestion
The image above illustrates the components of the root orchestrator. Each component operates as an independent service, integrated and managed using the Docker Compose plugin.
```

2024-12-18 15:28 UTC, nitindermohan commented on content/docs/concepts/scheduling.md
> +The networking requirements selection and geographic constraints support are coming out in our next release, **v0.5**, and are part of the LDP algorithm update. Stay tuned.
No longer necessary with the updated callout above

2024-12-19 08:28 UTC, giobart reviewed
LGTM, also I integrated your comments.

2024-12-19 09:24 UTC, nitindermohan approved these changes
This looks good now

2024-12-19 09:24 UTC, merged