Dev
nitindermohan/oak-new-docs pull request #25
Opened 2024-12-11 07:40 UTC by nitindermohan

PR for merging contribution guide

Added files
- contribution guide overview
- code of conduct
- Git Hooks

2024-12-11 10:43 UTC, giobart requested changes
Super cool! Just added my review comments :D

2024-12-11 10:43 UTC, giobart commented on content/docs/contribution-guide/contributing-guide.md
> +# Contributing Overview
```suggestion
```
This title can be removed otw Hugo shows it twice
<img width="512" alt="image" src="https://github.com/user-attachments/assets/1aa15813-9072-49a4-9312-368b9cd68645">

2024-12-11 10:43 UTC, giobart commented on content/docs/contribution-guide/contributing-guide.md
> +Oakestra is a welcoming, collaborative, and inclusive community. We want Oakestra to be a place where contributors feel empowered to share ideas, ask questions, and grow. All contributors are expecte
```suggestion
Oakestra is a welcoming, collaborative, and inclusive community. We want Oakestra to be a place where contributors feel empowered to share ideas, ask questions, and grow. All contributors are expected to follow our _Code of Conduct_ to keep our community positive and open.
```

I guess you meant to underline the text?

2024-12-11 10:43 UTC, giobart commented on content/docs/contribution-guide/contributing-guide.md
> +Oakestra is committed to a respectful and inclusive environment. By contributing, you agree to abide by our [Code of Conduct](#link-to-code-of-conduct).
```suggestion
Oakestra is committed to a respectful and inclusive environment. By contributing, you agree to abide by our [Code of Conduct](../code-of-conduct/).
```

2024-12-11 10:43 UTC, giobart commented on content/docs/contribution-guide/contributing-guide.md
> +If you are eager to start contributing code right away, we have a list of [good first issues](https://github.com/oakestra/oakestra/labels/good%20first%20issue) that contain bugs which have a relative
good first issues are usually the beginner-friendly ones, while help wanted all the rest. Also we need to specify how they can get the issue assigned. Here a suggestion:

```suggestion
If you are eager to start contributing code right away, we have a list of [good first issues](https://github.com/oakestra/oakestra/labels/good%20first%20issue) that contain bugs which have a relatively limited scope. Alternatively, you can ceck for issues labeled as [“help wanted”](https://github.com/oakestra/oakestra/labels/help%20wanted) for feature extensions that have not been handled yet. As you gain more experience and demonstrate a commitment to evolving Oakestra, you may be granted issue management permissions in the repository.

**How to contribute?** Just comment on an unassigned issue, stating you want to work on it. Once you get an ACK, you'll get assigned to a branch related to the issue. All your work must be merged to the assigned branch first via Pull Request. 
```

2024-12-11 10:43 UTC, giobart commented on hugo_stats.json
this file currently has a conflict

2024-12-11 10:54 UTC, nitindermohan commented on hugo_stats.json
Should be fine now.

2024-12-11 13:07 UTC, nitindermohan commented
@giobart thank you for your comments. I also just added the code style guide doc to the PR. Can you please review it as well?

2024-12-11 15:21 UTC, giobart reviewed
Everything looks veery good. There is only one issue with the PyCharm/VSCode tables (at least on safari) but I think this issue is related to Doks. Specifically, when clicking PyCharm/VSCode the page jumps to a different VSCode/PyCharm table in the same page. As you see the tables are actually switching but the page anchors are messed up. I think that if there is no immediate solution we can ignore this for now.
![ScreenRecording2024-12-11at16 16 43-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/817984a4-dbb2-4945-b644-abf2556b970c)

2024-12-12 08:26 UTC, nitindermohan commented
Discussed the concern pointed out by @giobart (in comment https://github.com/nitindermohan/oak-new-docs/pull/25#pullrequestreview-2496012361) in the meeting and it appears like a browser-specific issue of Doks. The bug appears in Safari but not in Chrome. 

Doks is planning to make a new release soon and hopefully this will be addressed with it.

2024-12-12 08:34 UTC, merged